---
title: "___"
author: "Achille Dekkers, Maxime Pourtois, Oguzhan Dogru, Tanguy Deprez "
format:
  html:
    code-fold: true
    code-tools: true
    toc: true
editor: visual
lang: fr
---

<!--# Ceci est un commentaire. -->

<!--% Ceci est une consigne. Ne jamais modifier ni déplacer les consignes dans le document ! -->

<!--% Complétez le titre et le nom des auteurs (auteur1, auteur2, auteur3 et auteur 4) dans l'entête YAML.-->

## Introduction et but

<!--% Rédigez une courte introduction de 3 ou 5 phrases qui présente vos données. Ajoutez une phrase de but. Vous devez citer la bibliographie en utilisant le formatage Markdown ad hoc et en incluant votre référence au format bibtex dans le fichier references.bib. -->

## Matériel et méthodes

<!--% Indiquez ici d'où viennent les données et aussi quel logiciel (et version) vous utilisez pour les analyses. Inspirez-vous des projets déjà réalisés. -->

...Matériel et méthodes...

## Analyses

<!--% Lisez bien les éléments devant guider votre analyse proposée dans le README.-->

```{r setup, include=FALSE}
# Nécessaire pour les tests SDD, ne pas utiliser dans un "vrai" projet
if (!"tools:tests" %in% search())
  source(here::here("tests/tools_tests.R"), attach(NULL, name = "tools:tests"))
# Configuration de l'environnement
SciViews::R("ts", lang = "fr")
feur <- read("data/mobility_wallonia.rds")
```

<!--% Ajoutez le nombre de chunks que vous souhaitez. Répartissez-vous le travail correctement. Structurez la section en partie avec des titres explicites de niveau trois.-->

```{r}

feur %>.%
  smutate(., 
    "retail" = retail_and_recreation_percent_change_from_baseline,
    "grocery" = grocery_and_pharmacy_percent_change_from_baseline,
    "parks" = parks_percent_change_from_baseline,
    "transit" = transit_stations_percent_change_from_baseline,
    "workplaces" = workplaces_percent_change_from_baseline,
    "residential" = residential_percent_change_from_baseline,
     retail = labelise(retail_and_recreation_percent_change_from_baseline, "Variation du pourcentage de la fréquentation des zones de vente au détail et des loisirs par rapport à la base"),
    grocery = labelise(grocery, "Variation du pourcentage de la fréquentation des épiceries et pharmacies par rapport au niveau de base"), 
    parks = labelise(parks, "Variation du pourcentage de la fréquentation des parcs"), 
      transit = labelise(transit, "Variation en pourcentage de la fréquentation des stations de transit par rapport à la référence"), 
      workplaces = labelise(workplaces, "Variation en pourcentage de la fréquentation des lieux de travail par rapport à la base"),
      residential = labelise(residential, "Variation en pourcentage de la fréquentation des zones résidentielles par rapport à la base")
  ) -> feur
sselect(feur, c(1, 8, 9, 10, 11, 12, 13)) -> feur

```

```{r}
par(mfrow = c(3,2), mar = c(2,2,2,2))
retail_ts <- ts(feur$retail, start = c(2020, 46), frequency = 365)
grocery_ts <- ts(feur$grocery,  start = c(2020, 46), frequency = 365)
parks_ts <- ts(feur$parks,  start = c(2020, 46), frequency = 365)
transit_ts <- ts(feur$transit,  start = c(2020, 46), frequency = 365)
workplaces_ts <- ts(feur$workplaces,  start = c(2020, 46), frequency = 365)
residential_ts <- ts(feur$residential,  start = c(2020, 46), frequency = 365)
plot(retail_ts, main = "Fréquentation des lieux de vente au détail et loisirs")
plot(grocery_ts, main = "Fréquentation des épiceries et pharmacies")
plot(parks_ts, main = "Fréquentation des parcs")
plot(transit_ts, main = "Fréquentation des stations de transit")
plot(workplaces_ts, main = "Fréquentation des lieux de travail")
plot(residential_ts,main = "Fréquentation des zones résidentielles")

```

```{r Autocrrélation,spectre, tendantce des séries brutes}

set.seed(9037)
#par(mfrow = c(3,2), mar = c(2,2,2,2))
acf(retail_ts)
spectrum(retail_ts, spans = c(3, 5), main = "Fréquentation des lieux de vente au détail et loisirs")
retail_ts_trend<-trend.test(retail_ts, R = 999)
plot(retail_ts_trend)

acf(grocery_ts)
spectrum(grocery_ts, spans = c(3, 5), main = "Fréquentation des épiceries et pharmacies")
grocery_ts_trend<-trend.test(grocery_ts, R = 999)
plot(grocery_ts_trend)

#acf(parks_ts)
#spectrum(parks_ts, spans = c(3, 5), main = "Fréquentation des parcs")

acf(transit_ts)
spectrum(transit_ts, spans = c(3,5), main = "Fréquentation des stations de transit")
transit_ts_trend<-trend.test(transit_ts, R = 999)
plot(transit_ts_trend)

acf(workplaces_ts)
spectrum(workplaces_ts, spans = c(3,5), main = "Fréquentation des lieux de travail")
workplaces_ts_trend<-trend.test(workplaces_ts, R = 999)
plot(workplaces_ts_trend)


acf(residential_ts)
spectrum(residential_ts, spans = c(3,5),main = "Fréquentation des zones résidentielles")
residential_ts_trend<-trend.test(residential_ts, R = 999)
plot(residential_ts_trend, main = "Fréquentation des zones résidentielles")
# APPAREMMENT PAS DE TENDANCE POUR LA ZONE RESIDENTIELLE DONC PEUT ETRE PAS IMPORTANT 
# ESSAYER DE VOIR  si DIFFERENCE ENTRE PRE CONFINEMENT-CONFINEMENT-POST CONFINEMENT
# On peut regarder aussi différence semaine et weekend, peut être pour les mêmes périodes
#
```

```{r }
retail_diff<-tsd(retail_ts, method = "average", s.window = "periodic")
retail_loess<-tsd(retail_ts, method = "loess", s.window = 7, trend = TRUE)
plot(retail_diff)
plot(retail_loess, col = c(1:3))

retail_filt <- extract(retail_diff, components = "filtered")
spectrum(retail_filt, spans = c(3, 5))

retail_resid <- extract(retail_diff, components = "residuals")
spectrum(retail_resid, spans = c(3, 5))

retail_mts<-tseries(retail_loess)
fspec <- spectrum(retail_mts[, "seasonal"],spans = c(3,5))
rsspec <- spectrum(retail_mts[, "residuals"],spans = c(3,5))
```

```{r retail précovid}
retail_ts_conf<-window(retail_ts, end = c(2020, 126))
retail_diff_conf<-tsd(retail_ts_conf, method = "average", s.window = "periodic")

acf(retail_ts_conf)
plot(retail_diff_conf)

retail_filt_conf <- extract(retail_diff_conf, components = "filtered")
spectrum(retail_filt_conf, spans = c(3, 5))
```

```{r}

```



## Conclusion

<!--% Lorsque toutes les analyses sont réalisées, terminez ce bloc-notes avec 3 à 6 phrases de conclusion en rapport avec ce que vous avez observé dans vos analyses. Quels sont les éléments les plus pertinents que vous retenez ? -->

...vos conclusions ici...
